In [ ]:
import pandas as pd 
df = pd.read_csv('loan_data_set.csv')

df.head()

# 1.clean

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

In [ ]:
df['Gender'].dtypes

In [ ]:
df['Gender'].isnull().sum()
df['Gender'].mode()[0]
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [ ]:
df["LoanAmount"].mean()

In [67]:
# Replace the null values
for i in df.columns:
    # print(i)
    if df[i].dtypes =="O":
        # print(i)
        df[i] = df[i].fillna(df[i].mode()[0])
        df[i]=df[i].str.lower()
    else:
        df[i]=df[i].fillna(df[i].mean())

In [ ]:
df.isnull().sum()

In [ ]:
df['Dependents'].unique()

In [69]:
df

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,male,no,0,graduate,no,5849,0.0,146.412162,360.0,1.0,urban,1
1,male,yes,1,graduate,no,4583,1508.0,128.000000,360.0,1.0,rural,0
2,male,yes,0,graduate,yes,3000,0.0,66.000000,360.0,1.0,urban,1
3,male,yes,0,not graduate,no,2583,2358.0,120.000000,360.0,1.0,urban,1
4,male,no,0,graduate,no,6000,0.0,141.000000,360.0,1.0,urban,1
...,...,...,...,...,...,...,...,...,...,...,...,...
609,female,no,0,graduate,no,2900,0.0,71.000000,360.0,1.0,rural,1
610,male,yes,3+,graduate,no,4106,0.0,40.000000,180.0,1.0,rural,1
611,male,yes,1,graduate,no,8072,240.0,253.000000,360.0,1.0,urban,1
612,male,yes,2,graduate,no,7583,0.0,187.000000,360.0,1.0,urban,1
613,female,no,0,graduate,yes,4583,0.0,133.000000,360.0,0.0,semiurban,0

## datatypes check and replace

In [70]:
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,male,no,0,graduate,no,5849,0.0,146.412162,360.0,1.0,urban,1
1,male,yes,1,graduate,no,4583,1508.0,128.000000,360.0,1.0,rural,0
2,male,yes,0,graduate,yes,3000,0.0,66.000000,360.0,1.0,urban,1
3,male,yes,0,not graduate,no,2583,2358.0,120.000000,360.0,1.0,urban,1
4,male,no,0,graduate,no,6000,0.0,141.000000,360.0,1.0,urban,1

In [71]:
# 2. data Preprocessing
df = df.drop("Loan_ID",axis=1)

KeyError: "['Loan_ID'] not found in axis"

In [72]:
# N=0
# Y=1
# df["Loan_Status"] = df["Loan_Status"].map({"N":0,"Y":1})
from sklearn.preprocessing import LabelEncoder
l =LabelEncoder()
df["Loan_Status"] = l.fit_transform(df["Loan_Status"])
df.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,male,no,0,graduate,no,5849,0.0,146.412162,360.0,1.0,urban,1
1,male,yes,1,graduate,no,4583,1508.0,128.000000,360.0,1.0,rural,0
2,male,yes,0,graduate,yes,3000,0.0,66.000000,360.0,1.0,urban,1
3,male,yes,0,not graduate,no,2583,2358.0,120.000000,360.0,1.0,urban,1
4,male,no,0,graduate,no,6000,0.0,141.000000,360.0,1.0,urban,1

In [73]:
df.head(1)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,male,no,0,graduate,no,5849,0.0,146.412162,360.0,1.0,urban,1

## start the machine learning Training

In [74]:
# split data into x and y
# split data in training and testing
# apply column transform for preprocessing in one line 
# Load the Classification model and fit the model
# Predict the test data
# accuracy check
# then start predictions

In [75]:
df.head(1)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,male,no,0,graduate,no,5849,0.0,146.412162,360.0,1.0,urban,1

In [76]:
df['Education'].unique()

array(['graduate', 'not graduate'], dtype=object)

In [77]:
# split data into x and y
x= df.drop('Loan_Status',axis=1)
y =df['Loan_Status']

# train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

X_train.shape

# apply column transform for preprocessing in one line 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,OrdinalEncoder

columns_trans = ColumnTransformer([
        ('gender', OrdinalEncoder(), ['Gender']),
        ('married', OrdinalEncoder(), ['Married']),
        ('dependents', OrdinalEncoder(), ['Dependents']),
        ('education', OrdinalEncoder(), ['Education']),
        ('self_employed', OrdinalEncoder(), ['Self_Employed']),
        ('property_area',OneHotEncoder(sparse_output=False, handle_unknown='ignore'),['Property_Area']),
        ('scaler',StandardScaler(),['ApplicantIncome', 'CoapplicantIncome'])
    ],remainder='passthrough')

In [78]:
# model load
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
from sklearn.pipeline import make_pipeline
final = make_pipeline(columns_trans,model)
final

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('gender', OrdinalEncoder(),
                                                  ['Gender']),
                                                 ('married', OrdinalEncoder(),
                                                  ['Married']),
                                                 ('dependents',
                                                  OrdinalEncoder(),
                                                  ['Dependents']),
                                                 ('education', OrdinalEncoder(),
                                                  ['Education']),
                                                 ('self_employed',
                                                  OrdinalEncoder(),
                                                  ['Self_Employed']),
                                                 ('property_area',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Property_Area']),
                                                 ('scaler', StandardScaler(),
                                                  ['ApplicantIncome',
                                                   'CoapplicantIncome'])])),
                ('logisticregression', LogisticRegression())])

In [79]:
final.fit(X_train,y_train)

c:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\hp\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

c:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\hp\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('gender', OrdinalEncoder(),
                                                  ['Gender']),
                                                 ('married', OrdinalEncoder(),
                                                  ['Married']),
                                                 ('dependents',
                                                  OrdinalEncoder(),
                                                  ['Dependents']),
                                                 ('education', OrdinalEncoder(),
                                                  ['Education']),
                                                 ('self_employed',
                                                  OrdinalEncoder(),
                                                  ['Self_Employed']),
                                                 ('property_area',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['Property_Area']),
                                                 ('scaler', StandardScaler(),
                                                  ['ApplicantIncome',
                                                   'CoapplicantIncome'])])),
                ('logisticregression', LogisticRegression())])

In [80]:
print(final.score(X_train,y_train))
print(final.score(X_test,y_test))

0.8167006109979633
0.7886178861788617

In [81]:
y_pred = final.predict(X_test)

In [82]:
# Performance Matrix
# Measuring Performance metrics-Lost and Cost Function (MAE,MSE,RMSE,R2 Score)
# cost functions --> calculate erros
from sklearn.metrics import mean_absolute_error, mean_squared_error,root_mean_squared_error

print("MAE:",mean_absolute_error(y_test,y_pred))
print("MSE:",mean_squared_error(y_test,y_pred))
print("RMSE:",root_mean_squared_error(y_test,y_pred))

MAE: 0.21138211382113822
MSE: 0.21138211382113822
RMSE: 0.4597631061983315

In [83]:
from sklearn.metrics import (accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.7886178861788617
Precision: 0.7596153846153846
Recall: 0.9875
F1 Score: 0.8586956521739131

Confusion Matrix:
[[18 25]
 [ 1 79]]

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.42      0.58        43
           1       0.76      0.99      0.86        80

    accuracy                           0.79       123
   macro avg       0.85      0.70      0.72       123
weighted avg       0.83      0.79      0.76       123

In [84]:
x.sample(1)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
373,male,no,1,graduate,no,3062,1987.0,111.0,180.0,0.0,urban

In [85]:
a = final.predict(x.sample(1))[0]
a

np.int64(1)

In [86]:
if a==0:
    print("reject the loan")
else:
    print("loan approve")

loan approve

In [87]:
# save the model 
import pickle
pickle.dump(final , open("final_model.pkl","wb"))

In [88]:
# load and predict
model = pickle.load(open("final_model.pkl", "rb"))

In [89]:
x.dtypes

Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
dtype: object

In [90]:
# user input 
Gender = input("Enter your gender: ")
Married = input("Are you married? (Yes/No): ")
Dependents = input("Enter number of dependents (0/1/2/3+): ")
Education = input("Enter education (Graduate/Not Graduate): ")
Self_Employed = input("Are you self-employed? (Yes/No): ")
ApplicantIncome = int(input("Enter applicant income: "))
CoapplicantIncome = float(input("Enter coapplicant income: "))
LoanAmount = float(input("Enter loan amount: "))
Loan_Amount_Term = float(input("Enter loan amount term (in days): "))
Credit_History = float(input("Enter credit history (0/1): "))
Property_Area = input("Enter property area (Urban/Semiurban/Rural): ")

data = [[Gender, Married, Dependents, Education, Self_Employed, 
        ApplicantIncome, CoapplicantIncome, LoanAmount, Loan_Amount_Term, Credit_History, Property_Area]]

In [91]:
data = pd.DataFrame(data, columns=[
    'Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
    'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
    'Loan_Amount_Term', 'Credit_History', 'Property_Area'
])
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,male,yes,2,graduate,yes,3000,2000.0,20000.0,364.0,1.0,urban

In [92]:
model.predict(data)

array([0])

In [93]:
result = model.predict(data)
if result == 0:
    print("Loan rejected")
else:
    print("Loan Approved")

Loan rejected